defaults:
  - model: openai

# Path to the training and validation data
train_path: data/shakespeare/train.csv
valid_path: data/shakespeare/validation.csv
test_path: data/shakespeare/test.csv

# Reduce the data for development
development: False # 20000 or False

# Weight and biases
wandb_enabled: True
wandb_log_config: True