defaults:
  - model: gpt_nano

# Path to the training and validation data
train_path: data/text8/train.parquet
valid_path: data/text8/validation.parquet
test_path: data/text8/test.parquet

# Reduce the data for development
development: False # 20000 or False

# Weight and biases
wandb_enabled: True
wandb_log_config: True