defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# Path to the dataset
train_path: data/train.parquet
val_path: data/validation.parquet

# Hugging face tokenizer
token_name: gpt2

