defaults:
  - _self_

dataloader:
  _target_: torch.utils.data.DataLoader
  batch_size: 6
  num_workers: 5
  prefetch_factor: 2
  dataset:
    _target_: src.training.datasets.main_dataset.MainDataset
    p_bert: 0.05
    p_augment: 0.00
    block_size: 1024

torch_trainer:
  _target_: src.training.main_trainer.MainTrainer
  epochs: 30
  patience: 30
  learning_rate: 6e-3
  save_model: False
  scheduler_param:
    t_initial: 40
    warmup_t: 1
    warmup_lr_init: 1e-5
  model:
    _target_: src.training.models.gpt_model.GPT
    vocab_size: 50304
    n_embedding: 768
    block_size: 1024
    n_layer: 6
    n_head: 8
    dropout: 0.0
    bias: True
    kv_heads: 4
    grouped: False