defaults:
  - _self_

torch_trainer:
  _target_: src.training.main_trainer.MainTrainer
  epochs: 20
  patience: 5
  batch_size: 6
  learning_rate: 6e-4
  save_model: True
  scheduler_param:
    t_initial: 40
    warmup_t: 1
    warmup_lr_init: 1e-5
  model:
    _target_: src.training.models.gpt_model.GPT
    block_size: 512
    vocab_size: 50304
    n_embedding: 512
    n_layer: 4
    n_head: 8
    dropout: 0.0
    bias: True
