defaults:
  - _self_

dataloader:
  _target_: torch.utils.data.DataLoader
  batch_size: 20
  num_workers: 5
  prefetch_factor: 2
  dataset:
    _target_: src.training.datasets.main_dataset.MainDataset
    p_bert: 0.05
    p_augment: 0.1
    block_size: 512

torch_trainer:
  _target_: src.training.main_trainer.MainTrainer
  epochs: 20
  patience: 5
  learning_rate: 6e-4
  save_model: True
  scheduler_param:
    t_initial: 40
    warmup_t: 1
    warmup_lr_init: 1e-5
  model:
    _target_: src.training.models.gpt_model.GPT
    block_size: 512
    vocab_size: 50304
    n_embedding: 512
    n_layer: 4
    n_head: 8
    dropout: 0.0
    bias: True