dataloader:
  _target_: torch.utils.data.DataLoader
  batch_size: 3
  num_workers: 5
  prefetch_factor: 2
  dataset:
    _target_: src.training.datasets.main_dataset.MainDataset
    p_bert: 0.05
    p_augment: 0.00
    block_size: 1024

torch_trainer:
  _target_: src.training.main_trainer.MainTrainer
  epochs: 10
  patience: 10
  learning_rate: 6e-4
  save_model: False
  scheduler_param:
    t_initial: 40
    warmup_t: 1
    warmup_lr_init: 1e-5
  model:
    _target_: src.training.models.openai.OpenAI
    model_name: gpt2